[package]
name = "rs-1brc"
version = "0.1.0"
edition = "2021"

[dependencies]
bstr = "=1.6.0"
memchr = "=2.7.1"
crossbeam-channel = "0.5.12"
fast-float = "0.2.0"
ahash = "0.8.11"
hashbrown = "0.14.3"
