name: dew it Go

on:
    workflow_dispatch:

jobs:
  Go:
    name: dew it in Go
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up graalvm to gen data
        uses: graalvm/setup-graalvm@v1
        with:
            distribution: 'graalvm'
            version: '22.3.2'
            java-version: '21.0.2'
            components: 'native-image'
      - name: BIG FAT DATA
        run: |
            mvn clean install
            ./create_measurements.sh 1000000000
            ls -lrthS
      - name: Setup GO 1.22
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.0-rc.1'
      - name: With GO we run
        run: |
          go build dew_it.go
          ./dew_it